# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /goinfre/qmanamel/.brew/Cellar/cmake/3.12.0/bin/cmake

# The command to remove a file.
RM = /goinfre/qmanamel/.brew/Cellar/cmake/3.12.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /goinfre/qmanamel/Documents/WeThinkCode_/Modules/C++/Bomberman

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /goinfre/qmanamel/Documents/WeThinkCode_/Modules/C++/Bomberman

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/goinfre/qmanamel/.brew/Cellar/cmake/3.12.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/goinfre/qmanamel/.brew/Cellar/cmake/3.12.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/goinfre/qmanamel/.brew/Cellar/cmake/3.12.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/goinfre/qmanamel/.brew/Cellar/cmake/3.12.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/goinfre/qmanamel/.brew/Cellar/cmake/3.12.0/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/goinfre/qmanamel/.brew/Cellar/cmake/3.12.0/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/goinfre/qmanamel/.brew/Cellar/cmake/3.12.0/bin/cpack --config ./CPackSourceConfig.cmake /goinfre/qmanamel/Documents/WeThinkCode_/Modules/C++/Bomberman/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/goinfre/qmanamel/.brew/Cellar/cmake/3.12.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/goinfre/qmanamel/.brew/Cellar/cmake/3.12.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/goinfre/qmanamel/.brew/Cellar/cmake/3.12.0/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /goinfre/qmanamel/Documents/WeThinkCode_/Modules/C++/Bomberman/CMakeFiles /goinfre/qmanamel/Documents/WeThinkCode_/Modules/C++/Bomberman/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /goinfre/qmanamel/Documents/WeThinkCode_/Modules/C++/Bomberman/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BomberMan

# Build rule for target.
BomberMan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BomberMan
.PHONY : BomberMan

# fast build rule for target.
BomberMan/fast:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/build
.PHONY : BomberMan/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) -f _deps/glad-build/CMakeFiles/glad.dir/build.make _deps/glad-build/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named glad-generate-files

# Build rule for target.
glad-generate-files: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glad-generate-files
.PHONY : glad-generate-files

# fast build rule for target.
glad-generate-files/fast:
	$(MAKE) -f _deps/glad-build/CMakeFiles/glad-generate-files.dir/build.make _deps/glad-build/CMakeFiles/glad-generate-files.dir/build
.PHONY : glad-generate-files/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f _deps/glfw-build/CMakeFiles/uninstall.dir/build.make _deps/glfw-build/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f _deps/glfw-build/src/CMakeFiles/glfw.dir/build.make _deps/glfw-build/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named glm_shared

# Build rule for target.
glm_shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glm_shared
.PHONY : glm_shared

# fast build rule for target.
glm_shared/fast:
	$(MAKE) -f _deps/glm-build/glm/CMakeFiles/glm_shared.dir/build.make _deps/glm-build/glm/CMakeFiles/glm_shared.dir/build
.PHONY : glm_shared/fast

#=============================================================================
# Target rules for targets named glm_static

# Build rule for target.
glm_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glm_static
.PHONY : glm_static

# fast build rule for target.
glm_static/fast:
	$(MAKE) -f _deps/glm-build/glm/CMakeFiles/glm_static.dir/build.make _deps/glm-build/glm/CMakeFiles/glm_static.dir/build
.PHONY : glm_static/fast

#=============================================================================
# Target rules for targets named dist

# Build rule for target.
dist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dist
.PHONY : dist

# fast build rule for target.
dist/fast:
	$(MAKE) -f _deps/freetype-build/CMakeFiles/dist.dir/build.make _deps/freetype-build/CMakeFiles/dist.dir/build
.PHONY : dist/fast

#=============================================================================
# Target rules for targets named freetype

# Build rule for target.
freetype: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freetype
.PHONY : freetype

# fast build rule for target.
freetype/fast:
	$(MAKE) -f _deps/freetype-build/CMakeFiles/freetype.dir/build.make _deps/freetype-build/CMakeFiles/freetype.dir/build
.PHONY : freetype/fast

Build/Components/Engine/sources/Engine.o: Build/Components/Engine/sources/Engine.cpp.o

.PHONY : Build/Components/Engine/sources/Engine.o

# target to build an object file
Build/Components/Engine/sources/Engine.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/Engine/sources/Engine.cpp.o
.PHONY : Build/Components/Engine/sources/Engine.cpp.o

Build/Components/Engine/sources/Engine.i: Build/Components/Engine/sources/Engine.cpp.i

.PHONY : Build/Components/Engine/sources/Engine.i

# target to preprocess a source file
Build/Components/Engine/sources/Engine.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/Engine/sources/Engine.cpp.i
.PHONY : Build/Components/Engine/sources/Engine.cpp.i

Build/Components/Engine/sources/Engine.s: Build/Components/Engine/sources/Engine.cpp.s

.PHONY : Build/Components/Engine/sources/Engine.s

# target to generate assembly for a file
Build/Components/Engine/sources/Engine.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/Engine/sources/Engine.cpp.s
.PHONY : Build/Components/Engine/sources/Engine.cpp.s

Build/Components/Engine/sources/Model.o: Build/Components/Engine/sources/Model.cpp.o

.PHONY : Build/Components/Engine/sources/Model.o

# target to build an object file
Build/Components/Engine/sources/Model.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/Engine/sources/Model.cpp.o
.PHONY : Build/Components/Engine/sources/Model.cpp.o

Build/Components/Engine/sources/Model.i: Build/Components/Engine/sources/Model.cpp.i

.PHONY : Build/Components/Engine/sources/Model.i

# target to preprocess a source file
Build/Components/Engine/sources/Model.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/Engine/sources/Model.cpp.i
.PHONY : Build/Components/Engine/sources/Model.cpp.i

Build/Components/Engine/sources/Model.s: Build/Components/Engine/sources/Model.cpp.s

.PHONY : Build/Components/Engine/sources/Model.s

# target to generate assembly for a file
Build/Components/Engine/sources/Model.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/Engine/sources/Model.cpp.s
.PHONY : Build/Components/Engine/sources/Model.cpp.s

Build/Components/Engine/sources/Shader.o: Build/Components/Engine/sources/Shader.cpp.o

.PHONY : Build/Components/Engine/sources/Shader.o

# target to build an object file
Build/Components/Engine/sources/Shader.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/Engine/sources/Shader.cpp.o
.PHONY : Build/Components/Engine/sources/Shader.cpp.o

Build/Components/Engine/sources/Shader.i: Build/Components/Engine/sources/Shader.cpp.i

.PHONY : Build/Components/Engine/sources/Shader.i

# target to preprocess a source file
Build/Components/Engine/sources/Shader.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/Engine/sources/Shader.cpp.i
.PHONY : Build/Components/Engine/sources/Shader.cpp.i

Build/Components/Engine/sources/Shader.s: Build/Components/Engine/sources/Shader.cpp.s

.PHONY : Build/Components/Engine/sources/Shader.s

# target to generate assembly for a file
Build/Components/Engine/sources/Shader.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/Engine/sources/Shader.cpp.s
.PHONY : Build/Components/Engine/sources/Shader.cpp.s

Build/Components/Engine/sources/Text.o: Build/Components/Engine/sources/Text.cpp.o

.PHONY : Build/Components/Engine/sources/Text.o

# target to build an object file
Build/Components/Engine/sources/Text.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/Engine/sources/Text.cpp.o
.PHONY : Build/Components/Engine/sources/Text.cpp.o

Build/Components/Engine/sources/Text.i: Build/Components/Engine/sources/Text.cpp.i

.PHONY : Build/Components/Engine/sources/Text.i

# target to preprocess a source file
Build/Components/Engine/sources/Text.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/Engine/sources/Text.cpp.i
.PHONY : Build/Components/Engine/sources/Text.cpp.i

Build/Components/Engine/sources/Text.s: Build/Components/Engine/sources/Text.cpp.s

.PHONY : Build/Components/Engine/sources/Text.s

# target to generate assembly for a file
Build/Components/Engine/sources/Text.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/Engine/sources/Text.cpp.s
.PHONY : Build/Components/Engine/sources/Text.cpp.s

Build/Components/Game/sources/Game.o: Build/Components/Game/sources/Game.cpp.o

.PHONY : Build/Components/Game/sources/Game.o

# target to build an object file
Build/Components/Game/sources/Game.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/Game/sources/Game.cpp.o
.PHONY : Build/Components/Game/sources/Game.cpp.o

Build/Components/Game/sources/Game.i: Build/Components/Game/sources/Game.cpp.i

.PHONY : Build/Components/Game/sources/Game.i

# target to preprocess a source file
Build/Components/Game/sources/Game.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/Game/sources/Game.cpp.i
.PHONY : Build/Components/Game/sources/Game.cpp.i

Build/Components/Game/sources/Game.s: Build/Components/Game/sources/Game.cpp.s

.PHONY : Build/Components/Game/sources/Game.s

# target to generate assembly for a file
Build/Components/Game/sources/Game.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/Game/sources/Game.cpp.s
.PHONY : Build/Components/Game/sources/Game.cpp.s

Build/Components/GameEngine/GUIManager/GUIManager.o: Build/Components/GameEngine/GUIManager/GUIManager.cpp.o

.PHONY : Build/Components/GameEngine/GUIManager/GUIManager.o

# target to build an object file
Build/Components/GameEngine/GUIManager/GUIManager.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GUIManager/GUIManager.cpp.o
.PHONY : Build/Components/GameEngine/GUIManager/GUIManager.cpp.o

Build/Components/GameEngine/GUIManager/GUIManager.i: Build/Components/GameEngine/GUIManager/GUIManager.cpp.i

.PHONY : Build/Components/GameEngine/GUIManager/GUIManager.i

# target to preprocess a source file
Build/Components/GameEngine/GUIManager/GUIManager.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GUIManager/GUIManager.cpp.i
.PHONY : Build/Components/GameEngine/GUIManager/GUIManager.cpp.i

Build/Components/GameEngine/GUIManager/GUIManager.s: Build/Components/GameEngine/GUIManager/GUIManager.cpp.s

.PHONY : Build/Components/GameEngine/GUIManager/GUIManager.s

# target to generate assembly for a file
Build/Components/GameEngine/GUIManager/GUIManager.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GUIManager/GUIManager.cpp.s
.PHONY : Build/Components/GameEngine/GUIManager/GUIManager.cpp.s

Build/Components/GameEngine/GameObjects/sources/Bomb.o: Build/Components/GameEngine/GameObjects/sources/Bomb.cpp.o

.PHONY : Build/Components/GameEngine/GameObjects/sources/Bomb.o

# target to build an object file
Build/Components/GameEngine/GameObjects/sources/Bomb.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GameObjects/sources/Bomb.cpp.o
.PHONY : Build/Components/GameEngine/GameObjects/sources/Bomb.cpp.o

Build/Components/GameEngine/GameObjects/sources/Bomb.i: Build/Components/GameEngine/GameObjects/sources/Bomb.cpp.i

.PHONY : Build/Components/GameEngine/GameObjects/sources/Bomb.i

# target to preprocess a source file
Build/Components/GameEngine/GameObjects/sources/Bomb.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GameObjects/sources/Bomb.cpp.i
.PHONY : Build/Components/GameEngine/GameObjects/sources/Bomb.cpp.i

Build/Components/GameEngine/GameObjects/sources/Bomb.s: Build/Components/GameEngine/GameObjects/sources/Bomb.cpp.s

.PHONY : Build/Components/GameEngine/GameObjects/sources/Bomb.s

# target to generate assembly for a file
Build/Components/GameEngine/GameObjects/sources/Bomb.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GameObjects/sources/Bomb.cpp.s
.PHONY : Build/Components/GameEngine/GameObjects/sources/Bomb.cpp.s

Build/Components/GameEngine/GameObjects/sources/Door.o: Build/Components/GameEngine/GameObjects/sources/Door.cpp.o

.PHONY : Build/Components/GameEngine/GameObjects/sources/Door.o

# target to build an object file
Build/Components/GameEngine/GameObjects/sources/Door.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GameObjects/sources/Door.cpp.o
.PHONY : Build/Components/GameEngine/GameObjects/sources/Door.cpp.o

Build/Components/GameEngine/GameObjects/sources/Door.i: Build/Components/GameEngine/GameObjects/sources/Door.cpp.i

.PHONY : Build/Components/GameEngine/GameObjects/sources/Door.i

# target to preprocess a source file
Build/Components/GameEngine/GameObjects/sources/Door.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GameObjects/sources/Door.cpp.i
.PHONY : Build/Components/GameEngine/GameObjects/sources/Door.cpp.i

Build/Components/GameEngine/GameObjects/sources/Door.s: Build/Components/GameEngine/GameObjects/sources/Door.cpp.s

.PHONY : Build/Components/GameEngine/GameObjects/sources/Door.s

# target to generate assembly for a file
Build/Components/GameEngine/GameObjects/sources/Door.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GameObjects/sources/Door.cpp.s
.PHONY : Build/Components/GameEngine/GameObjects/sources/Door.cpp.s

Build/Components/GameEngine/GameObjects/sources/Enemy.o: Build/Components/GameEngine/GameObjects/sources/Enemy.cpp.o

.PHONY : Build/Components/GameEngine/GameObjects/sources/Enemy.o

# target to build an object file
Build/Components/GameEngine/GameObjects/sources/Enemy.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GameObjects/sources/Enemy.cpp.o
.PHONY : Build/Components/GameEngine/GameObjects/sources/Enemy.cpp.o

Build/Components/GameEngine/GameObjects/sources/Enemy.i: Build/Components/GameEngine/GameObjects/sources/Enemy.cpp.i

.PHONY : Build/Components/GameEngine/GameObjects/sources/Enemy.i

# target to preprocess a source file
Build/Components/GameEngine/GameObjects/sources/Enemy.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GameObjects/sources/Enemy.cpp.i
.PHONY : Build/Components/GameEngine/GameObjects/sources/Enemy.cpp.i

Build/Components/GameEngine/GameObjects/sources/Enemy.s: Build/Components/GameEngine/GameObjects/sources/Enemy.cpp.s

.PHONY : Build/Components/GameEngine/GameObjects/sources/Enemy.s

# target to generate assembly for a file
Build/Components/GameEngine/GameObjects/sources/Enemy.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GameObjects/sources/Enemy.cpp.s
.PHONY : Build/Components/GameEngine/GameObjects/sources/Enemy.cpp.s

Build/Components/GameEngine/GameObjects/sources/GameObject.o: Build/Components/GameEngine/GameObjects/sources/GameObject.cpp.o

.PHONY : Build/Components/GameEngine/GameObjects/sources/GameObject.o

# target to build an object file
Build/Components/GameEngine/GameObjects/sources/GameObject.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GameObjects/sources/GameObject.cpp.o
.PHONY : Build/Components/GameEngine/GameObjects/sources/GameObject.cpp.o

Build/Components/GameEngine/GameObjects/sources/GameObject.i: Build/Components/GameEngine/GameObjects/sources/GameObject.cpp.i

.PHONY : Build/Components/GameEngine/GameObjects/sources/GameObject.i

# target to preprocess a source file
Build/Components/GameEngine/GameObjects/sources/GameObject.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GameObjects/sources/GameObject.cpp.i
.PHONY : Build/Components/GameEngine/GameObjects/sources/GameObject.cpp.i

Build/Components/GameEngine/GameObjects/sources/GameObject.s: Build/Components/GameEngine/GameObjects/sources/GameObject.cpp.s

.PHONY : Build/Components/GameEngine/GameObjects/sources/GameObject.s

# target to generate assembly for a file
Build/Components/GameEngine/GameObjects/sources/GameObject.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GameObjects/sources/GameObject.cpp.s
.PHONY : Build/Components/GameEngine/GameObjects/sources/GameObject.cpp.s

Build/Components/GameEngine/GameObjects/sources/Player.o: Build/Components/GameEngine/GameObjects/sources/Player.cpp.o

.PHONY : Build/Components/GameEngine/GameObjects/sources/Player.o

# target to build an object file
Build/Components/GameEngine/GameObjects/sources/Player.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GameObjects/sources/Player.cpp.o
.PHONY : Build/Components/GameEngine/GameObjects/sources/Player.cpp.o

Build/Components/GameEngine/GameObjects/sources/Player.i: Build/Components/GameEngine/GameObjects/sources/Player.cpp.i

.PHONY : Build/Components/GameEngine/GameObjects/sources/Player.i

# target to preprocess a source file
Build/Components/GameEngine/GameObjects/sources/Player.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GameObjects/sources/Player.cpp.i
.PHONY : Build/Components/GameEngine/GameObjects/sources/Player.cpp.i

Build/Components/GameEngine/GameObjects/sources/Player.s: Build/Components/GameEngine/GameObjects/sources/Player.cpp.s

.PHONY : Build/Components/GameEngine/GameObjects/sources/Player.s

# target to generate assembly for a file
Build/Components/GameEngine/GameObjects/sources/Player.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GameObjects/sources/Player.cpp.s
.PHONY : Build/Components/GameEngine/GameObjects/sources/Player.cpp.s

Build/Components/GameEngine/GameObjects/sources/SolidWall.o: Build/Components/GameEngine/GameObjects/sources/SolidWall.cpp.o

.PHONY : Build/Components/GameEngine/GameObjects/sources/SolidWall.o

# target to build an object file
Build/Components/GameEngine/GameObjects/sources/SolidWall.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GameObjects/sources/SolidWall.cpp.o
.PHONY : Build/Components/GameEngine/GameObjects/sources/SolidWall.cpp.o

Build/Components/GameEngine/GameObjects/sources/SolidWall.i: Build/Components/GameEngine/GameObjects/sources/SolidWall.cpp.i

.PHONY : Build/Components/GameEngine/GameObjects/sources/SolidWall.i

# target to preprocess a source file
Build/Components/GameEngine/GameObjects/sources/SolidWall.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GameObjects/sources/SolidWall.cpp.i
.PHONY : Build/Components/GameEngine/GameObjects/sources/SolidWall.cpp.i

Build/Components/GameEngine/GameObjects/sources/SolidWall.s: Build/Components/GameEngine/GameObjects/sources/SolidWall.cpp.s

.PHONY : Build/Components/GameEngine/GameObjects/sources/SolidWall.s

# target to generate assembly for a file
Build/Components/GameEngine/GameObjects/sources/SolidWall.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GameObjects/sources/SolidWall.cpp.s
.PHONY : Build/Components/GameEngine/GameObjects/sources/SolidWall.cpp.s

Build/Components/GameEngine/GameObjects/sources/Wall.o: Build/Components/GameEngine/GameObjects/sources/Wall.cpp.o

.PHONY : Build/Components/GameEngine/GameObjects/sources/Wall.o

# target to build an object file
Build/Components/GameEngine/GameObjects/sources/Wall.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GameObjects/sources/Wall.cpp.o
.PHONY : Build/Components/GameEngine/GameObjects/sources/Wall.cpp.o

Build/Components/GameEngine/GameObjects/sources/Wall.i: Build/Components/GameEngine/GameObjects/sources/Wall.cpp.i

.PHONY : Build/Components/GameEngine/GameObjects/sources/Wall.i

# target to preprocess a source file
Build/Components/GameEngine/GameObjects/sources/Wall.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GameObjects/sources/Wall.cpp.i
.PHONY : Build/Components/GameEngine/GameObjects/sources/Wall.cpp.i

Build/Components/GameEngine/GameObjects/sources/Wall.s: Build/Components/GameEngine/GameObjects/sources/Wall.cpp.s

.PHONY : Build/Components/GameEngine/GameObjects/sources/Wall.s

# target to generate assembly for a file
Build/Components/GameEngine/GameObjects/sources/Wall.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/GameObjects/sources/Wall.cpp.s
.PHONY : Build/Components/GameEngine/GameObjects/sources/Wall.cpp.s

Build/Components/GameEngine/LevelManager/LevelManager.o: Build/Components/GameEngine/LevelManager/LevelManager.cpp.o

.PHONY : Build/Components/GameEngine/LevelManager/LevelManager.o

# target to build an object file
Build/Components/GameEngine/LevelManager/LevelManager.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/LevelManager/LevelManager.cpp.o
.PHONY : Build/Components/GameEngine/LevelManager/LevelManager.cpp.o

Build/Components/GameEngine/LevelManager/LevelManager.i: Build/Components/GameEngine/LevelManager/LevelManager.cpp.i

.PHONY : Build/Components/GameEngine/LevelManager/LevelManager.i

# target to preprocess a source file
Build/Components/GameEngine/LevelManager/LevelManager.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/LevelManager/LevelManager.cpp.i
.PHONY : Build/Components/GameEngine/LevelManager/LevelManager.cpp.i

Build/Components/GameEngine/LevelManager/LevelManager.s: Build/Components/GameEngine/LevelManager/LevelManager.cpp.s

.PHONY : Build/Components/GameEngine/LevelManager/LevelManager.s

# target to generate assembly for a file
Build/Components/GameEngine/LevelManager/LevelManager.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/LevelManager/LevelManager.cpp.s
.PHONY : Build/Components/GameEngine/LevelManager/LevelManager.cpp.s

Build/Components/GameEngine/ObjectManager/ObjectManager.o: Build/Components/GameEngine/ObjectManager/ObjectManager.cpp.o

.PHONY : Build/Components/GameEngine/ObjectManager/ObjectManager.o

# target to build an object file
Build/Components/GameEngine/ObjectManager/ObjectManager.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/ObjectManager/ObjectManager.cpp.o
.PHONY : Build/Components/GameEngine/ObjectManager/ObjectManager.cpp.o

Build/Components/GameEngine/ObjectManager/ObjectManager.i: Build/Components/GameEngine/ObjectManager/ObjectManager.cpp.i

.PHONY : Build/Components/GameEngine/ObjectManager/ObjectManager.i

# target to preprocess a source file
Build/Components/GameEngine/ObjectManager/ObjectManager.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/ObjectManager/ObjectManager.cpp.i
.PHONY : Build/Components/GameEngine/ObjectManager/ObjectManager.cpp.i

Build/Components/GameEngine/ObjectManager/ObjectManager.s: Build/Components/GameEngine/ObjectManager/ObjectManager.cpp.s

.PHONY : Build/Components/GameEngine/ObjectManager/ObjectManager.s

# target to generate assembly for a file
Build/Components/GameEngine/ObjectManager/ObjectManager.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/ObjectManager/ObjectManager.cpp.s
.PHONY : Build/Components/GameEngine/ObjectManager/ObjectManager.cpp.s

Build/Components/GameEngine/Vector3d/Vector3d.o: Build/Components/GameEngine/Vector3d/Vector3d.cpp.o

.PHONY : Build/Components/GameEngine/Vector3d/Vector3d.o

# target to build an object file
Build/Components/GameEngine/Vector3d/Vector3d.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/Vector3d/Vector3d.cpp.o
.PHONY : Build/Components/GameEngine/Vector3d/Vector3d.cpp.o

Build/Components/GameEngine/Vector3d/Vector3d.i: Build/Components/GameEngine/Vector3d/Vector3d.cpp.i

.PHONY : Build/Components/GameEngine/Vector3d/Vector3d.i

# target to preprocess a source file
Build/Components/GameEngine/Vector3d/Vector3d.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/Vector3d/Vector3d.cpp.i
.PHONY : Build/Components/GameEngine/Vector3d/Vector3d.cpp.i

Build/Components/GameEngine/Vector3d/Vector3d.s: Build/Components/GameEngine/Vector3d/Vector3d.cpp.s

.PHONY : Build/Components/GameEngine/Vector3d/Vector3d.s

# target to generate assembly for a file
Build/Components/GameEngine/Vector3d/Vector3d.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/GameEngine/Vector3d/Vector3d.cpp.s
.PHONY : Build/Components/GameEngine/Vector3d/Vector3d.cpp.s

Build/Components/Sound/sources/Sound.o: Build/Components/Sound/sources/Sound.cpp.o

.PHONY : Build/Components/Sound/sources/Sound.o

# target to build an object file
Build/Components/Sound/sources/Sound.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/Sound/sources/Sound.cpp.o
.PHONY : Build/Components/Sound/sources/Sound.cpp.o

Build/Components/Sound/sources/Sound.i: Build/Components/Sound/sources/Sound.cpp.i

.PHONY : Build/Components/Sound/sources/Sound.i

# target to preprocess a source file
Build/Components/Sound/sources/Sound.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/Sound/sources/Sound.cpp.i
.PHONY : Build/Components/Sound/sources/Sound.cpp.i

Build/Components/Sound/sources/Sound.s: Build/Components/Sound/sources/Sound.cpp.s

.PHONY : Build/Components/Sound/sources/Sound.s

# target to generate assembly for a file
Build/Components/Sound/sources/Sound.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/Components/Sound/sources/Sound.cpp.s
.PHONY : Build/Components/Sound/sources/Sound.cpp.s

Build/States/sources/Credits.o: Build/States/sources/Credits.cpp.o

.PHONY : Build/States/sources/Credits.o

# target to build an object file
Build/States/sources/Credits.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/Credits.cpp.o
.PHONY : Build/States/sources/Credits.cpp.o

Build/States/sources/Credits.i: Build/States/sources/Credits.cpp.i

.PHONY : Build/States/sources/Credits.i

# target to preprocess a source file
Build/States/sources/Credits.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/Credits.cpp.i
.PHONY : Build/States/sources/Credits.cpp.i

Build/States/sources/Credits.s: Build/States/sources/Credits.cpp.s

.PHONY : Build/States/sources/Credits.s

# target to generate assembly for a file
Build/States/sources/Credits.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/Credits.cpp.s
.PHONY : Build/States/sources/Credits.cpp.s

Build/States/sources/Intro.o: Build/States/sources/Intro.cpp.o

.PHONY : Build/States/sources/Intro.o

# target to build an object file
Build/States/sources/Intro.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/Intro.cpp.o
.PHONY : Build/States/sources/Intro.cpp.o

Build/States/sources/Intro.i: Build/States/sources/Intro.cpp.i

.PHONY : Build/States/sources/Intro.i

# target to preprocess a source file
Build/States/sources/Intro.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/Intro.cpp.i
.PHONY : Build/States/sources/Intro.cpp.i

Build/States/sources/Intro.s: Build/States/sources/Intro.cpp.s

.PHONY : Build/States/sources/Intro.s

# target to generate assembly for a file
Build/States/sources/Intro.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/Intro.cpp.s
.PHONY : Build/States/sources/Intro.cpp.s

Build/States/sources/Menu.o: Build/States/sources/Menu.cpp.o

.PHONY : Build/States/sources/Menu.o

# target to build an object file
Build/States/sources/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/Menu.cpp.o
.PHONY : Build/States/sources/Menu.cpp.o

Build/States/sources/Menu.i: Build/States/sources/Menu.cpp.i

.PHONY : Build/States/sources/Menu.i

# target to preprocess a source file
Build/States/sources/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/Menu.cpp.i
.PHONY : Build/States/sources/Menu.cpp.i

Build/States/sources/Menu.s: Build/States/sources/Menu.cpp.s

.PHONY : Build/States/sources/Menu.s

# target to generate assembly for a file
Build/States/sources/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/Menu.cpp.s
.PHONY : Build/States/sources/Menu.cpp.s

Build/States/sources/MenuParentState.o: Build/States/sources/MenuParentState.cpp.o

.PHONY : Build/States/sources/MenuParentState.o

# target to build an object file
Build/States/sources/MenuParentState.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/MenuParentState.cpp.o
.PHONY : Build/States/sources/MenuParentState.cpp.o

Build/States/sources/MenuParentState.i: Build/States/sources/MenuParentState.cpp.i

.PHONY : Build/States/sources/MenuParentState.i

# target to preprocess a source file
Build/States/sources/MenuParentState.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/MenuParentState.cpp.i
.PHONY : Build/States/sources/MenuParentState.cpp.i

Build/States/sources/MenuParentState.s: Build/States/sources/MenuParentState.cpp.s

.PHONY : Build/States/sources/MenuParentState.s

# target to generate assembly for a file
Build/States/sources/MenuParentState.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/MenuParentState.cpp.s
.PHONY : Build/States/sources/MenuParentState.cpp.s

Build/States/sources/Options.o: Build/States/sources/Options.cpp.o

.PHONY : Build/States/sources/Options.o

# target to build an object file
Build/States/sources/Options.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/Options.cpp.o
.PHONY : Build/States/sources/Options.cpp.o

Build/States/sources/Options.i: Build/States/sources/Options.cpp.i

.PHONY : Build/States/sources/Options.i

# target to preprocess a source file
Build/States/sources/Options.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/Options.cpp.i
.PHONY : Build/States/sources/Options.cpp.i

Build/States/sources/Options.s: Build/States/sources/Options.cpp.s

.PHONY : Build/States/sources/Options.s

# target to generate assembly for a file
Build/States/sources/Options.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/Options.cpp.s
.PHONY : Build/States/sources/Options.cpp.s

Build/States/sources/OptionsControls.o: Build/States/sources/OptionsControls.cpp.o

.PHONY : Build/States/sources/OptionsControls.o

# target to build an object file
Build/States/sources/OptionsControls.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/OptionsControls.cpp.o
.PHONY : Build/States/sources/OptionsControls.cpp.o

Build/States/sources/OptionsControls.i: Build/States/sources/OptionsControls.cpp.i

.PHONY : Build/States/sources/OptionsControls.i

# target to preprocess a source file
Build/States/sources/OptionsControls.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/OptionsControls.cpp.i
.PHONY : Build/States/sources/OptionsControls.cpp.i

Build/States/sources/OptionsControls.s: Build/States/sources/OptionsControls.cpp.s

.PHONY : Build/States/sources/OptionsControls.s

# target to generate assembly for a file
Build/States/sources/OptionsControls.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/OptionsControls.cpp.s
.PHONY : Build/States/sources/OptionsControls.cpp.s

Build/States/sources/OptionsFullScreen.o: Build/States/sources/OptionsFullScreen.cpp.o

.PHONY : Build/States/sources/OptionsFullScreen.o

# target to build an object file
Build/States/sources/OptionsFullScreen.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/OptionsFullScreen.cpp.o
.PHONY : Build/States/sources/OptionsFullScreen.cpp.o

Build/States/sources/OptionsFullScreen.i: Build/States/sources/OptionsFullScreen.cpp.i

.PHONY : Build/States/sources/OptionsFullScreen.i

# target to preprocess a source file
Build/States/sources/OptionsFullScreen.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/OptionsFullScreen.cpp.i
.PHONY : Build/States/sources/OptionsFullScreen.cpp.i

Build/States/sources/OptionsFullScreen.s: Build/States/sources/OptionsFullScreen.cpp.s

.PHONY : Build/States/sources/OptionsFullScreen.s

# target to generate assembly for a file
Build/States/sources/OptionsFullScreen.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/OptionsFullScreen.cpp.s
.PHONY : Build/States/sources/OptionsFullScreen.cpp.s

Build/States/sources/OptionsResolution.o: Build/States/sources/OptionsResolution.cpp.o

.PHONY : Build/States/sources/OptionsResolution.o

# target to build an object file
Build/States/sources/OptionsResolution.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/OptionsResolution.cpp.o
.PHONY : Build/States/sources/OptionsResolution.cpp.o

Build/States/sources/OptionsResolution.i: Build/States/sources/OptionsResolution.cpp.i

.PHONY : Build/States/sources/OptionsResolution.i

# target to preprocess a source file
Build/States/sources/OptionsResolution.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/OptionsResolution.cpp.i
.PHONY : Build/States/sources/OptionsResolution.cpp.i

Build/States/sources/OptionsResolution.s: Build/States/sources/OptionsResolution.cpp.s

.PHONY : Build/States/sources/OptionsResolution.s

# target to generate assembly for a file
Build/States/sources/OptionsResolution.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/OptionsResolution.cpp.s
.PHONY : Build/States/sources/OptionsResolution.cpp.s

Build/States/sources/OptionsVolume.o: Build/States/sources/OptionsVolume.cpp.o

.PHONY : Build/States/sources/OptionsVolume.o

# target to build an object file
Build/States/sources/OptionsVolume.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/OptionsVolume.cpp.o
.PHONY : Build/States/sources/OptionsVolume.cpp.o

Build/States/sources/OptionsVolume.i: Build/States/sources/OptionsVolume.cpp.i

.PHONY : Build/States/sources/OptionsVolume.i

# target to preprocess a source file
Build/States/sources/OptionsVolume.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/OptionsVolume.cpp.i
.PHONY : Build/States/sources/OptionsVolume.cpp.i

Build/States/sources/OptionsVolume.s: Build/States/sources/OptionsVolume.cpp.s

.PHONY : Build/States/sources/OptionsVolume.s

# target to generate assembly for a file
Build/States/sources/OptionsVolume.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/OptionsVolume.cpp.s
.PHONY : Build/States/sources/OptionsVolume.cpp.s

Build/States/sources/Pause.o: Build/States/sources/Pause.cpp.o

.PHONY : Build/States/sources/Pause.o

# target to build an object file
Build/States/sources/Pause.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/Pause.cpp.o
.PHONY : Build/States/sources/Pause.cpp.o

Build/States/sources/Pause.i: Build/States/sources/Pause.cpp.i

.PHONY : Build/States/sources/Pause.i

# target to preprocess a source file
Build/States/sources/Pause.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/Pause.cpp.i
.PHONY : Build/States/sources/Pause.cpp.i

Build/States/sources/Pause.s: Build/States/sources/Pause.cpp.s

.PHONY : Build/States/sources/Pause.s

# target to generate assembly for a file
Build/States/sources/Pause.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/Pause.cpp.s
.PHONY : Build/States/sources/Pause.cpp.s

Build/States/sources/PauseQuit.o: Build/States/sources/PauseQuit.cpp.o

.PHONY : Build/States/sources/PauseQuit.o

# target to build an object file
Build/States/sources/PauseQuit.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/PauseQuit.cpp.o
.PHONY : Build/States/sources/PauseQuit.cpp.o

Build/States/sources/PauseQuit.i: Build/States/sources/PauseQuit.cpp.i

.PHONY : Build/States/sources/PauseQuit.i

# target to preprocess a source file
Build/States/sources/PauseQuit.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/PauseQuit.cpp.i
.PHONY : Build/States/sources/PauseQuit.cpp.i

Build/States/sources/PauseQuit.s: Build/States/sources/PauseQuit.cpp.s

.PHONY : Build/States/sources/PauseQuit.s

# target to generate assembly for a file
Build/States/sources/PauseQuit.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/PauseQuit.cpp.s
.PHONY : Build/States/sources/PauseQuit.cpp.s

Build/States/sources/PauseResume.o: Build/States/sources/PauseResume.cpp.o

.PHONY : Build/States/sources/PauseResume.o

# target to build an object file
Build/States/sources/PauseResume.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/PauseResume.cpp.o
.PHONY : Build/States/sources/PauseResume.cpp.o

Build/States/sources/PauseResume.i: Build/States/sources/PauseResume.cpp.i

.PHONY : Build/States/sources/PauseResume.i

# target to preprocess a source file
Build/States/sources/PauseResume.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/PauseResume.cpp.i
.PHONY : Build/States/sources/PauseResume.cpp.i

Build/States/sources/PauseResume.s: Build/States/sources/PauseResume.cpp.s

.PHONY : Build/States/sources/PauseResume.s

# target to generate assembly for a file
Build/States/sources/PauseResume.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/PauseResume.cpp.s
.PHONY : Build/States/sources/PauseResume.cpp.s

Build/States/sources/PauseSaveQuit.o: Build/States/sources/PauseSaveQuit.cpp.o

.PHONY : Build/States/sources/PauseSaveQuit.o

# target to build an object file
Build/States/sources/PauseSaveQuit.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/PauseSaveQuit.cpp.o
.PHONY : Build/States/sources/PauseSaveQuit.cpp.o

Build/States/sources/PauseSaveQuit.i: Build/States/sources/PauseSaveQuit.cpp.i

.PHONY : Build/States/sources/PauseSaveQuit.i

# target to preprocess a source file
Build/States/sources/PauseSaveQuit.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/PauseSaveQuit.cpp.i
.PHONY : Build/States/sources/PauseSaveQuit.cpp.i

Build/States/sources/PauseSaveQuit.s: Build/States/sources/PauseSaveQuit.cpp.s

.PHONY : Build/States/sources/PauseSaveQuit.s

# target to generate assembly for a file
Build/States/sources/PauseSaveQuit.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/PauseSaveQuit.cpp.s
.PHONY : Build/States/sources/PauseSaveQuit.cpp.s

Build/States/sources/Play.o: Build/States/sources/Play.cpp.o

.PHONY : Build/States/sources/Play.o

# target to build an object file
Build/States/sources/Play.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/Play.cpp.o
.PHONY : Build/States/sources/Play.cpp.o

Build/States/sources/Play.i: Build/States/sources/Play.cpp.i

.PHONY : Build/States/sources/Play.i

# target to preprocess a source file
Build/States/sources/Play.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/Play.cpp.i
.PHONY : Build/States/sources/Play.cpp.i

Build/States/sources/Play.s: Build/States/sources/Play.cpp.s

.PHONY : Build/States/sources/Play.s

# target to generate assembly for a file
Build/States/sources/Play.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/Play.cpp.s
.PHONY : Build/States/sources/Play.cpp.s

Build/States/sources/Quit.o: Build/States/sources/Quit.cpp.o

.PHONY : Build/States/sources/Quit.o

# target to build an object file
Build/States/sources/Quit.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/Quit.cpp.o
.PHONY : Build/States/sources/Quit.cpp.o

Build/States/sources/Quit.i: Build/States/sources/Quit.cpp.i

.PHONY : Build/States/sources/Quit.i

# target to preprocess a source file
Build/States/sources/Quit.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/Quit.cpp.i
.PHONY : Build/States/sources/Quit.cpp.i

Build/States/sources/Quit.s: Build/States/sources/Quit.cpp.s

.PHONY : Build/States/sources/Quit.s

# target to generate assembly for a file
Build/States/sources/Quit.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/States/sources/Quit.cpp.s
.PHONY : Build/States/sources/Quit.cpp.s

Build/main.o: Build/main.cpp.o

.PHONY : Build/main.o

# target to build an object file
Build/main.cpp.o:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/main.cpp.o
.PHONY : Build/main.cpp.o

Build/main.i: Build/main.cpp.i

.PHONY : Build/main.i

# target to preprocess a source file
Build/main.cpp.i:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/main.cpp.i
.PHONY : Build/main.cpp.i

Build/main.s: Build/main.cpp.s

.PHONY : Build/main.s

# target to generate assembly for a file
Build/main.cpp.s:
	$(MAKE) -f CMakeFiles/BomberMan.dir/build.make CMakeFiles/BomberMan.dir/Build/main.cpp.s
.PHONY : Build/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... package"
	@echo "... BomberMan"
	@echo "... glad"
	@echo "... glad-generate-files"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... glm_shared"
	@echo "... glm_static"
	@echo "... dist"
	@echo "... freetype"
	@echo "... Build/Components/Engine/sources/Engine.o"
	@echo "... Build/Components/Engine/sources/Engine.i"
	@echo "... Build/Components/Engine/sources/Engine.s"
	@echo "... Build/Components/Engine/sources/Model.o"
	@echo "... Build/Components/Engine/sources/Model.i"
	@echo "... Build/Components/Engine/sources/Model.s"
	@echo "... Build/Components/Engine/sources/Shader.o"
	@echo "... Build/Components/Engine/sources/Shader.i"
	@echo "... Build/Components/Engine/sources/Shader.s"
	@echo "... Build/Components/Engine/sources/Text.o"
	@echo "... Build/Components/Engine/sources/Text.i"
	@echo "... Build/Components/Engine/sources/Text.s"
	@echo "... Build/Components/Game/sources/Game.o"
	@echo "... Build/Components/Game/sources/Game.i"
	@echo "... Build/Components/Game/sources/Game.s"
	@echo "... Build/Components/GameEngine/GUIManager/GUIManager.o"
	@echo "... Build/Components/GameEngine/GUIManager/GUIManager.i"
	@echo "... Build/Components/GameEngine/GUIManager/GUIManager.s"
	@echo "... Build/Components/GameEngine/GameObjects/sources/Bomb.o"
	@echo "... Build/Components/GameEngine/GameObjects/sources/Bomb.i"
	@echo "... Build/Components/GameEngine/GameObjects/sources/Bomb.s"
	@echo "... Build/Components/GameEngine/GameObjects/sources/Door.o"
	@echo "... Build/Components/GameEngine/GameObjects/sources/Door.i"
	@echo "... Build/Components/GameEngine/GameObjects/sources/Door.s"
	@echo "... Build/Components/GameEngine/GameObjects/sources/Enemy.o"
	@echo "... Build/Components/GameEngine/GameObjects/sources/Enemy.i"
	@echo "... Build/Components/GameEngine/GameObjects/sources/Enemy.s"
	@echo "... Build/Components/GameEngine/GameObjects/sources/GameObject.o"
	@echo "... Build/Components/GameEngine/GameObjects/sources/GameObject.i"
	@echo "... Build/Components/GameEngine/GameObjects/sources/GameObject.s"
	@echo "... Build/Components/GameEngine/GameObjects/sources/Player.o"
	@echo "... Build/Components/GameEngine/GameObjects/sources/Player.i"
	@echo "... Build/Components/GameEngine/GameObjects/sources/Player.s"
	@echo "... Build/Components/GameEngine/GameObjects/sources/SolidWall.o"
	@echo "... Build/Components/GameEngine/GameObjects/sources/SolidWall.i"
	@echo "... Build/Components/GameEngine/GameObjects/sources/SolidWall.s"
	@echo "... Build/Components/GameEngine/GameObjects/sources/Wall.o"
	@echo "... Build/Components/GameEngine/GameObjects/sources/Wall.i"
	@echo "... Build/Components/GameEngine/GameObjects/sources/Wall.s"
	@echo "... Build/Components/GameEngine/LevelManager/LevelManager.o"
	@echo "... Build/Components/GameEngine/LevelManager/LevelManager.i"
	@echo "... Build/Components/GameEngine/LevelManager/LevelManager.s"
	@echo "... Build/Components/GameEngine/ObjectManager/ObjectManager.o"
	@echo "... Build/Components/GameEngine/ObjectManager/ObjectManager.i"
	@echo "... Build/Components/GameEngine/ObjectManager/ObjectManager.s"
	@echo "... Build/Components/GameEngine/Vector3d/Vector3d.o"
	@echo "... Build/Components/GameEngine/Vector3d/Vector3d.i"
	@echo "... Build/Components/GameEngine/Vector3d/Vector3d.s"
	@echo "... Build/Components/Sound/sources/Sound.o"
	@echo "... Build/Components/Sound/sources/Sound.i"
	@echo "... Build/Components/Sound/sources/Sound.s"
	@echo "... Build/States/sources/Credits.o"
	@echo "... Build/States/sources/Credits.i"
	@echo "... Build/States/sources/Credits.s"
	@echo "... Build/States/sources/Intro.o"
	@echo "... Build/States/sources/Intro.i"
	@echo "... Build/States/sources/Intro.s"
	@echo "... Build/States/sources/Menu.o"
	@echo "... Build/States/sources/Menu.i"
	@echo "... Build/States/sources/Menu.s"
	@echo "... Build/States/sources/MenuParentState.o"
	@echo "... Build/States/sources/MenuParentState.i"
	@echo "... Build/States/sources/MenuParentState.s"
	@echo "... Build/States/sources/Options.o"
	@echo "... Build/States/sources/Options.i"
	@echo "... Build/States/sources/Options.s"
	@echo "... Build/States/sources/OptionsControls.o"
	@echo "... Build/States/sources/OptionsControls.i"
	@echo "... Build/States/sources/OptionsControls.s"
	@echo "... Build/States/sources/OptionsFullScreen.o"
	@echo "... Build/States/sources/OptionsFullScreen.i"
	@echo "... Build/States/sources/OptionsFullScreen.s"
	@echo "... Build/States/sources/OptionsResolution.o"
	@echo "... Build/States/sources/OptionsResolution.i"
	@echo "... Build/States/sources/OptionsResolution.s"
	@echo "... Build/States/sources/OptionsVolume.o"
	@echo "... Build/States/sources/OptionsVolume.i"
	@echo "... Build/States/sources/OptionsVolume.s"
	@echo "... Build/States/sources/Pause.o"
	@echo "... Build/States/sources/Pause.i"
	@echo "... Build/States/sources/Pause.s"
	@echo "... Build/States/sources/PauseQuit.o"
	@echo "... Build/States/sources/PauseQuit.i"
	@echo "... Build/States/sources/PauseQuit.s"
	@echo "... Build/States/sources/PauseResume.o"
	@echo "... Build/States/sources/PauseResume.i"
	@echo "... Build/States/sources/PauseResume.s"
	@echo "... Build/States/sources/PauseSaveQuit.o"
	@echo "... Build/States/sources/PauseSaveQuit.i"
	@echo "... Build/States/sources/PauseSaveQuit.s"
	@echo "... Build/States/sources/Play.o"
	@echo "... Build/States/sources/Play.i"
	@echo "... Build/States/sources/Play.s"
	@echo "... Build/States/sources/Quit.o"
	@echo "... Build/States/sources/Quit.i"
	@echo "... Build/States/sources/Quit.s"
	@echo "... Build/main.o"
	@echo "... Build/main.i"
	@echo "... Build/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

