# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /goinfre/qmanamel/.brew/Cellar/cmake/3.12.0/bin/cmake

# The command to remove a file.
RM = /goinfre/qmanamel/.brew/Cellar/cmake/3.12.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /goinfre/qmanamel/Documents/WeThinkCode_/Modules/C++/Bomberman

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /goinfre/qmanamel/Documents/WeThinkCode_/Modules/C++/Bomberman

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/goinfre/qmanamel/.brew/Cellar/cmake/3.12.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/goinfre/qmanamel/.brew/Cellar/cmake/3.12.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /goinfre/qmanamel/Documents/WeThinkCode_/Modules/C++/Bomberman/CMakeFiles /goinfre/qmanamel/Documents/WeThinkCode_/Modules/C++/Bomberman/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /goinfre/qmanamel/Documents/WeThinkCode_/Modules/C++/Bomberman/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Bomberman

# Build rule for target.
Bomberman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Bomberman
.PHONY : Bomberman

# fast build rule for target.
Bomberman/fast:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/build
.PHONY : Bomberman/fast

Build/Game/Engine/sources/Engine.o: Build/Game/Engine/sources/Engine.cpp.o

.PHONY : Build/Game/Engine/sources/Engine.o

# target to build an object file
Build/Game/Engine/sources/Engine.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/Build/Game/Engine/sources/Engine.cpp.o
.PHONY : Build/Game/Engine/sources/Engine.cpp.o

Build/Game/Engine/sources/Engine.i: Build/Game/Engine/sources/Engine.cpp.i

.PHONY : Build/Game/Engine/sources/Engine.i

# target to preprocess a source file
Build/Game/Engine/sources/Engine.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/Build/Game/Engine/sources/Engine.cpp.i
.PHONY : Build/Game/Engine/sources/Engine.cpp.i

Build/Game/Engine/sources/Engine.s: Build/Game/Engine/sources/Engine.cpp.s

.PHONY : Build/Game/Engine/sources/Engine.s

# target to generate assembly for a file
Build/Game/Engine/sources/Engine.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/Build/Game/Engine/sources/Engine.cpp.s
.PHONY : Build/Game/Engine/sources/Engine.cpp.s

Build/Game/Game/sources/Game.o: Build/Game/Game/sources/Game.cpp.o

.PHONY : Build/Game/Game/sources/Game.o

# target to build an object file
Build/Game/Game/sources/Game.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/Build/Game/Game/sources/Game.cpp.o
.PHONY : Build/Game/Game/sources/Game.cpp.o

Build/Game/Game/sources/Game.i: Build/Game/Game/sources/Game.cpp.i

.PHONY : Build/Game/Game/sources/Game.i

# target to preprocess a source file
Build/Game/Game/sources/Game.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/Build/Game/Game/sources/Game.cpp.i
.PHONY : Build/Game/Game/sources/Game.cpp.i

Build/Game/Game/sources/Game.s: Build/Game/Game/sources/Game.cpp.s

.PHONY : Build/Game/Game/sources/Game.s

# target to generate assembly for a file
Build/Game/Game/sources/Game.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/Build/Game/Game/sources/Game.cpp.s
.PHONY : Build/Game/Game/sources/Game.cpp.s

Build/Game/Player/sources/Player.o: Build/Game/Player/sources/Player.cpp.o

.PHONY : Build/Game/Player/sources/Player.o

# target to build an object file
Build/Game/Player/sources/Player.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/Build/Game/Player/sources/Player.cpp.o
.PHONY : Build/Game/Player/sources/Player.cpp.o

Build/Game/Player/sources/Player.i: Build/Game/Player/sources/Player.cpp.i

.PHONY : Build/Game/Player/sources/Player.i

# target to preprocess a source file
Build/Game/Player/sources/Player.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/Build/Game/Player/sources/Player.cpp.i
.PHONY : Build/Game/Player/sources/Player.cpp.i

Build/Game/Player/sources/Player.s: Build/Game/Player/sources/Player.cpp.s

.PHONY : Build/Game/Player/sources/Player.s

# target to generate assembly for a file
Build/Game/Player/sources/Player.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/Build/Game/Player/sources/Player.cpp.s
.PHONY : Build/Game/Player/sources/Player.cpp.s

Build/States/Menu/sources/Menu.o: Build/States/Menu/sources/Menu.cpp.o

.PHONY : Build/States/Menu/sources/Menu.o

# target to build an object file
Build/States/Menu/sources/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/Build/States/Menu/sources/Menu.cpp.o
.PHONY : Build/States/Menu/sources/Menu.cpp.o

Build/States/Menu/sources/Menu.i: Build/States/Menu/sources/Menu.cpp.i

.PHONY : Build/States/Menu/sources/Menu.i

# target to preprocess a source file
Build/States/Menu/sources/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/Build/States/Menu/sources/Menu.cpp.i
.PHONY : Build/States/Menu/sources/Menu.cpp.i

Build/States/Menu/sources/Menu.s: Build/States/Menu/sources/Menu.cpp.s

.PHONY : Build/States/Menu/sources/Menu.s

# target to generate assembly for a file
Build/States/Menu/sources/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/Build/States/Menu/sources/Menu.cpp.s
.PHONY : Build/States/Menu/sources/Menu.cpp.s

Build/main.o: Build/main.cpp.o

.PHONY : Build/main.o

# target to build an object file
Build/main.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/Build/main.cpp.o
.PHONY : Build/main.cpp.o

Build/main.i: Build/main.cpp.i

.PHONY : Build/main.i

# target to preprocess a source file
Build/main.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/Build/main.cpp.i
.PHONY : Build/main.cpp.i

Build/main.s: Build/main.cpp.s

.PHONY : Build/main.s

# target to generate assembly for a file
Build/main.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/Build/main.cpp.s
.PHONY : Build/main.cpp.s

CMakeFiles/3.12.0/CompilerIdCXX/CMakeCXXCompilerId.o: CMakeFiles/3.12.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

.PHONY : CMakeFiles/3.12.0/CompilerIdCXX/CMakeCXXCompilerId.o

# target to build an object file
CMakeFiles/3.12.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/CMakeFiles/3.12.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : CMakeFiles/3.12.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

CMakeFiles/3.12.0/CompilerIdCXX/CMakeCXXCompilerId.i: CMakeFiles/3.12.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

.PHONY : CMakeFiles/3.12.0/CompilerIdCXX/CMakeCXXCompilerId.i

# target to preprocess a source file
CMakeFiles/3.12.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/CMakeFiles/3.12.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : CMakeFiles/3.12.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

CMakeFiles/3.12.0/CompilerIdCXX/CMakeCXXCompilerId.s: CMakeFiles/3.12.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

.PHONY : CMakeFiles/3.12.0/CompilerIdCXX/CMakeCXXCompilerId.s

# target to generate assembly for a file
CMakeFiles/3.12.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/CMakeFiles/3.12.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : CMakeFiles/3.12.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Bomberman"
	@echo "... Build/Game/Engine/sources/Engine.o"
	@echo "... Build/Game/Engine/sources/Engine.i"
	@echo "... Build/Game/Engine/sources/Engine.s"
	@echo "... Build/Game/Game/sources/Game.o"
	@echo "... Build/Game/Game/sources/Game.i"
	@echo "... Build/Game/Game/sources/Game.s"
	@echo "... Build/Game/Player/sources/Player.o"
	@echo "... Build/Game/Player/sources/Player.i"
	@echo "... Build/Game/Player/sources/Player.s"
	@echo "... Build/States/Menu/sources/Menu.o"
	@echo "... Build/States/Menu/sources/Menu.i"
	@echo "... Build/States/Menu/sources/Menu.s"
	@echo "... Build/main.o"
	@echo "... Build/main.i"
	@echo "... Build/main.s"
	@echo "... CMakeFiles/3.12.0/CompilerIdCXX/CMakeCXXCompilerId.o"
	@echo "... CMakeFiles/3.12.0/CompilerIdCXX/CMakeCXXCompilerId.i"
	@echo "... CMakeFiles/3.12.0/CompilerIdCXX/CMakeCXXCompilerId.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

